loremipsum/general/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import url, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
	path('about/', views.about, name='about'),
    path('', views.index, name='index'),
    path('api/events/', views.event_list, name='event_list'),
    path('api/events/<int:pk>/', views.event_detail, name='event_detail'),
	path('accounts/signup/', views.SignUpView.as_view(), name='signup'),
    path('accounts/signup/parent/', views.ParentSignUpView.as_view(), name='parent_signup'),
    path('accounts/signup/provider/', views.ProviderSignUpView.as_view(), name='provider_signup'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

loremipsum/loremipsum/urls.py
from django.urls import include, path
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tickets.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

loremipsum/tickets/models.py
from django.db import models
from django import forms
from django.conf import settings
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import AbstractUser
from django.utils.html import escape, mark_safe
from .search import EventPostIndex

class User(AbstractUser):
    is_parent = models.BooleanField('parent status', default = False)
    is_provider = models.BooleanField('provider status', default = False)

class Event(models.Model):
    AGE_RANGES = (
            ( "0005", "0-5"),
            ( "0609", "6-9"),
            ( "1012", "10-12"),
            ( "1314", "13-14"),
            )
    TYPES = (
            ( "1", "Παιδικά θέατρα"),
            ( "2", "Συναυλίες"),
            ( "3", "Παιδότοποι"),
            ( "4", "Πάρτυ"),
            ( "5", "Εκπαιδευτικές εκδρομές/εκδηλώσεις"),
            ( "6", "Αθλητικές δραστηριότητες"),
            ( "7", "Πάρκα αναψυχής"),
            ( "8", "Παιδικές κατασκηνώσεις"),
            )
    title = models.TextField(max_length=256)
    event_date = models.DateTimeField('event date')
    date_added = models.DateTimeField('Date added')
    capacity = models.IntegerField()
    availability = models.IntegerField()
    location = models.TextField(max_length=256)
    latitude = models.DecimalField(decimal_places=5, max_digits=7)
    longitude = models.DecimalField(decimal_places=5, max_digits=7)
    age_range = models.CharField(max_length=4, choices = AGE_RANGES, default="0005")
    event_type = models.CharField(max_length=1, choices = TYPES, default="1")
    cost = models.IntegerField()
    provider = models.ForeignKey('Provider', on_delete=models.CASCADE)
    hits = models.IntegerField()

    def get_absolute_url(self):
        return "/event/%i" % self.id
    def toJSON(self):
        return json.dumps(self, default=lambda o: o.__dict__,
            sort_keys=True)
    def __str__(self):
        return "%s (%s)" % (self.title, self.event_date)
    def indexing(self):
        obj = EventPostIndex(
                meta = { 'id': self.id },
                title = self.title,
                date = self.event_date,
                location = self.location,
                )
        obj.save()
        return obj.to_dict(include_meta=True)

class Provider(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,default='')
    full_name = models.TextField()
    email = models.EmailField()
    address = models.TextField(default='')
    afm = models.TextField()
    doy = models.TextField()
    legal_representative = models.TextField()
    adt = models.TextField()
    site = models.URLField()
    logo = models.ImageField(upload_to='media/')
    def get_absolute_url(self):
        return "/provider/%i" % self.user.id
    def __str__(self):
        return "%s" % self.full_name

class Parent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True,default='')
    email = models.EmailField(default='')
    full_name = models.TextField()
    address = models.TextField(default='')
    coins = models.IntegerField(default = 0)
    latitude = models.DecimalField(decimal_places=5, max_digits=7)
    longitude = models.DecimalField(decimal_places=5, max_digits=7)

class Review(models.Model):
    date = models.DateTimeField('review date')
    user = models.ForeignKey('Parent', on_delete =models.CASCADE)
    event = models.ForeignKey('Event', on_delete= models.CASCADE)
    content = models.TextField()
    rating = models.IntegerField()

class Tag(models.Model):
    name = models.TextField()

class TagEventAssociation(models.Model):
    event = models.ForeignKey('Event', on_delete = models.CASCADE)
    tag = models.ForeignKey('Tag', on_delete = models.CASCADE)

class Transaction(models.Model):
    event = models.ForeignKey('Event', on_delete = models.CASCADE)
    parent = models.ForeignKey(Parent, on_delete = models.CASCADE)
    date = models.DateTimeField("Purchase date")
    amount = models.IntegerField()
    total_cost = models.IntegerField()

loremipsum/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="shortcut icon" type="image/svg" href="favicon.svg"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../static/images/favicon.svg">

    <title>{% block head_title %}{% endblock %}Lorem Ipsum</title>

    <!-- Bootstrap core CSS -->
    <link href='{% static "css/bootstrap.min.css" %}' rel="stylesheet">

    <!-- Some plugin CSS -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='{% static "css/loremipsum.min.css" %}' rel="stylesheet">

    <!-- leaflet stuff -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.1/dist/leaflet.css" integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ==" crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.3.1/dist/leaflet.js" integrity="sha512-/Nsx9X4HebavoBvEBuyp3I7od5tA0UzAxs+j83KgC8PU0kgB4XiK4Lfe4y4cgBtaRJQEIFCW+oC506aPT2L1zw==" crossorigin=""></script>
  </head>

  <body>
    {% include 'navbar.html' %}

    {% block jumbotron %}
    {% endblock %}

    {% block maincontent %}
    {% endblock %}

    {% block content %}
    {% endblock %}

    {% block styles %}
    {% endblock %}


    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src='{% static "js/jquery.easing.js" %}'></script>

    <!-- Custom scripts -->
    <script src='{% static "js/lorem-ipsum.min.js" %}'></script>

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src='{% static "js/bootstrap.min.js" %}'></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>

loremipsum/templates/buy_coins.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% if user.is_authenticated %}
    {% if user.is_parent %}
        {% block styles %}
            <style>
                .jumbotron {
	           text-align: center;
                }
            </style>
        {% endblock %}

        {% block jumbotron %}
        <header class="masthead">
          <div class="container">
            <br>
            <img src="../../static/images/lorem-ipsum-shopping-cart.png" width="50%" alt=""><br><br>
          </div>
        </header>
        <div class="jumbotron">
            <h3>Αγόρασε το ποσό που επιθυμείς</h3><br>
            <p> 5€ = 750 Coins </p>
            <p> 10€ = 1500 Coins </p>
            <p> 20€ = 3000 + 75 Coins </p>
            <p> 50€ = 7500 + 150 Coins </p>
            <img src="../../static/images/payment.png" width="25%" alt=""><br><br>
        </div>
        {% endblock %}

        {% block content %}
        <div class="container">
          <div class="row">
            <div class="col-lg-4 text-center"></div>
            <div class="col-lg-4 text-center">
              <h3 class="section-heading text-uppercase">Αγορα Coins</h3>
              <h5 class="section-subheading text-muted">Συμπλήρωσε τα στοιχεία πληρωμής</h5><br>
              <form role="form" action="" method="post">
     	           {% csrf_token %}
     	           {{ form|crispy }}
     	           <button type="submit"> Αγορά </button>
 	           </form>
            </div>
            <div class="col-lg-4 text-center"></div>
          </div>
        </div><br>

        <footer>
        	<div class="container">
        		<div class="row">
        			<div class="col-md-4">
        				<span class="copyright">Copyright © Lorem Ipsum 2018</span>
        			</div>
        			<div class="col-md-4">
        				<ul class="list-inline social-buttons">
        					<li class="list-inline-item">
        						<a href="https://github.com/epilys/lorem-ipsum">
        							<i class="fa fa-github"></i>
        						</a>
        					</li>
        				</ul>
        			</div>
        			<div class="col-md-4"></div>
        		</div>
        	</div>
        </footer>
        {% endblock %}
    {% endif %}
{% endif %}

loremipsum/templates/buy_failure.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_title %}Αγορά {{ event.title }} {{ event.event_date }}{{ block.super }}{% endblock %}
{% block content %}
<header class="masthead">
  <div class="container">
    <br><br>
    <img src="../../static/images/lorem-ipsum-failure.png" width="50%" alt=""><br><br>
    <p> OOPS... </p><br>
  </div>
</header>

<section class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h3> Ανεπιτυχής αγορά...</h3>
        <div>
          <p>{{ reason }}</p>
        </div>
        <div class="row">
          <div class="col-lg-12 text-center">
            <a class="text-center btn btn-primary btn-md" href="{% url 'buy_coins' %}">Αγορά Coins</a>
            <a class="text-center btn btn-primary btn-md" href="/events/">Επιστροφή</a>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright © Lorem Ipsum 2018</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="https://github.com/epilys/lorem-ipsum">
              <i class="fa fa-github"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
</footer>
{% endblock %}

loremipsum/templates/buy_success.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_title %}Αγορά {{ event.title }} {{ event.event_date }}{{ block.super }}{% endblock %}
{% block content %}
<header class="masthead">
  <div class="container">
    <br><br>
    <img src="../../static/images/lorem-ipsum-success.png" width="50%" alt=""><br><br>
    <p> ΥΑΥ! </p><br>
  </div>
</header>

<section class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h3>Επιτυχής αγορά</h3><br>
        <div class="row"><br>
          <div class="col-lg-4 text-center"></div>
          <div class="col-lg-4 text-center">
            <table class="text-left">
              <tr>
                <td>Εκδήλωση</td>
                <td>{{ transaction.event.title }}<td>
              </tr>
              <tr>
                <td>Ημερομηνία</td>
                <td>{{ transaction.date }}<td>
              </tr>
              <tr>
                <td>Ποσότητα:</td>
                <td>{{ transaction.amount }}<td>
              </tr>
              <tr>
                <td>Συνολικό κόστος</td>
                <td>{{ transaction.total_cost }}<td>
              </tr>
            </table><br>

          </div>
        </div>
        <div>
          <p>Το νέο σας υπόλοιπο μετά από την αγορά είναι <b>{{ new_balance }}</b> coins</p>
        </div>
        <div class="row"><br>
          <div class="col-lg-12 text-center">
            <section id="portfolio" style="padding: 0">
      	      <div class="portfolio-item">
      	        <a class="portfolio-link" target="_blank" href="/tickets/ticketgen/receipt.pdf">
      	          <div class="portfolio-hover">
      	            <div class="portfolio-hover-content">
      	              <i class="fa fa-external-link fa-3x"></i>
      	            </div>
      	          </div>
      	          <img class="img-fluid" src="../../static/images/invoice.png" alt="">
      	        </a>
      	      </div>
          	</section>
          </div>
        </div>
        <br><div class="row"><br>
          <div class="col-lg-12 text-center">
            <a class="text-center btn btn-primary btn-md" href="{% url 'buy_coins' %}">Αγορά Coins</a>
            <a class="text-center btn btn-primary btn-md" href="/events/">Επιστροφή στις Εκδηλώσεις</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright © Lorem Ipsum 2018</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="https://github.com/epilys/lorem-ipsum">
              <i class="fa fa-github"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
</footer>
{% endblock %}

loremipsum/templates/event_buy.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_title %}Αγορά {{ event.title }} {{ event.event_date }}{{ block.super }}{% endblock %}
{% block content %}

<header class="masthead">
  <div class="container">
    <br><br>
    <img src="../../static/images/lorem-ipsum-business.png" width="50%" alt=""><br><br>
    <p> {{ event.title }} - {{ event.event_date}} </p><br>
  </div>
</header>

<section class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-4"></div>
      <div class="col-lg-4 text-left">
        <h4 class="text-center">Αγορά ενός εισιτηρίου για την εκδήλωση {{ event.title }}? </h4><br>
        <div>
          <form role="form" action="" method="post">
             {% csrf_token %}
             {{ form|crispy }}
             <div class="row"><br>
               <div class="col-lg-12 text-center"><br>
                 <button type="submit" class="text-center btn btn-primary btn-md" name="buy">Αγορά</button>
                 <button type="submit" class="text-center btn btn-primary btn-md" name="cancel">Ακύρωση</button>
               </div>
             </div>
          </form>
        </div>
      </div>
    </div>
  </div>~
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright © Lorem Ipsum 2018</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="https://github.com/epilys/lorem-ipsum">
              <i class="fa fa-github"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
</footer>
{% endblock %}

loremipsum/templates/event_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_title %}{{ event.title }} {{ event.event_date }}{{ block.super }}{% endblock %}
{% block content %}
<header class="masthead">
  <div class="container">
    <br><br>
    <img src="../../static/images/lorem-ipsum-rocket.png" width="50%" alt=""><br><br>
    <p> {{ event.title }} - {{ event.event_date}} </p><br>
  </div>
</header>

<section class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-4"></div>
      <div class="col-lg-4 text-left">
        <h4 class="text-center text-uppercase"> {{ event.title }} </h4><br>
        <div>
          <p><strong>Τίτλος</strong> {{ event.title }}</p>
          <p><strong>Ημερομηνία</strong> {{ event.event_date }}</p>
          <p><strong>Διαθέσιμα εισιτήρια</strong> {{ event.availability }}/{{ event.capacity }}</p>
          <p><strong>Τοποθεσία</strong> {{ event.location }}</p>
          <p><strong>Διοργανωτής</strong> <a href="{{ event.provider.get_absolute_url }}">{{ event.provider.full_name }}</a></p>
          <p><strong>Κόστος</strong> {{ event.cost }}</p>
          <p><strong>Τύπος</strong> {{ event.get_event_type_display }}</p>
          <p><strong>Ηλικιακό εύρος</strong> {{ event.get_age_range_display }}</p>
          <p><strong>Hits</strong> {{ event.hits }}</p>
        </div>
        <br><div class="row">
		      <div class="col-lg-12 text-center">
						<a class="text-center btn btn-secondary btn-md" href="{{ event.get_absolute_url }}/buy">Αγορά</a><br>
					</div>
				</div>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright © Lorem Ipsum 2018</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="https://github.com/epilys/lorem-ipsum">
              <i class="fa fa-github"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
</footer>
{% endblock %}

loremipsum/templates/event_list.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_title %}Καλωσήρθατε | {{ block.super }}{% endblock %}
{% block styles %}
    <style>
        .jumbotron {
     text-align: center;
        }
    </style>
{% endblock %}

{% block content %}
{% if filter.form %}
<header class="masthead">
  <div class="container">
    <br><br>
    <img src="../../static/images/lorem-ipsum-activities.png" width="50%" alt=""><br><br>
    <p>Αναζήτησε Δραστηριότητες</p><br>
  </div>
</header>

<section class="bg-light">
  <div class="container">
    <div class="col-lg-12 text-center">
      <img style="text-align: center" src="../../static/images/activities.png" width="50%" alt="">
    </div><br>
    <div class="row">
      <div class="col-lg-4">
        <form action="" method="get">
          <div class="form-group text-left">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-12">
                {{ filter.form.as_p }}
              </div>
            </div>
          </div>
          <input type="submit" class="btn btn-primary  text-center" value="Φιλτράρισμα"/><br><br>
        </form>
        <form action="" method="post" class="form-group">
          {% csrf_token %}
          {{ search_form.as_p }}
          <input type="submit" class="btn btn-primary" value="Ελεύθερη αναζήτηση" />
        </form>
      </div>
      <div class="col-lg-8 text-center">
        <h4> Αποτελέσματα σε ακτίνα 5χμ από την απόσταση σας</h4><br>
        <!-- username is loremipsum2018,  pass is vz0,&</:A'FQlpQ:9MhL:/@U/%%,deGgea_CrDqiHv03[s~i8b^h`#y}vKV/6lfZ -->
        <div id="event-list-map" style="height: 600px"></div>
      </div>
    </div>
    <br><br><div class="row">
      <div class="col-lg-12 text-center">
        {% if event_list %}
        <input class="form-control" id="table-event-filter-input" type="text" placeholder="Φιλτράρισμα">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Τίτλος</th>
              <th>Ημερομηνία</th>
              <th>Πάροχος</th>
              <th>Κόστος</th>
              <th>Διαθεσιμότητα</th>
              <th>Ηλ. εύρος</th>
              <th></th>
            </tr>
          </thead>
          <tbody id="table-event">
            {% for e in event_list %}
            <tr>
              <td>
                <a href="{{ e.get_absolute_url }}">{{ e.title }}</a>
              </td>
              <td>{{ e.event_date }}</td>
              <td>{{ e.provider }}</td>
              <td>{{ e.cost }}</td>
              <td>{{ e.availability }}/{{ e.capacity}}</td>
              <td>{{ e.get_age_range_display }}</td>
              <td><a href="{{ e.get_absolute_url }}/buy" class="btn btn-default">Αγορά</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% load json_filters %}
        {% else %}
        0 αποτελέσματα.
        {% endif %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script>
        $(document).ready(function(){
          var mymap = L.map('event-list-map').setView([{{ location.lat }}, {{ location.lon }}], 13);
          L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibG9yZW1pcHN1bTIwMTgiLCJhIjoiY2pkejE3bzBhMTNnYTJ4dGI2aTUzZXQ3NiJ9._Oc3vUq2Vn3uXqzphs-yrw', {
              attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, Imagery © <a href="http://mapbox.com">Mapbox</a>',
              maxZoom: 18,
              id: 'mapbox.light',
              accessToken: 'pk.eyJ1IjoibG9yZW1pcHN1bTIwMTgiLCJhIjoiY2pkejE3bzBhMTNnYTJ4dGI2aTUzZXQ3NiJ9._Oc3vUq2Vn3uXqzphs-yrw'
              }).addTo(mymap);
          var event_list = {{ event_list | jsonify | safe }};
            for (var e of event_list) {
              /*console.log(e);*/
              var marker = L.marker([e.latitude, e.longitude]).addTo(mymap);
              var popup = marker.bindPopup("<h2><a href=\"/event/" + e.id +"\">"+ e.title + "</a></h2><strong>Κόστος</strong>" + e.cost +"<br /><strong>Ηλ. εύρος</strong>"+ e.age_range +"<br/><strong>Διαθεσιμότητα</strong> "+ e.availability +"/"+ e.capacity);

            }
            var home_location = L.circle([{{ location.lat }}, {{ location.lon }}], { color: "#ab3659", radius: 50, fillColor: "#ab3659", fillOpacity: 0.5 }).addTo(mymap);
            var popup = home_location.bindPopup("Η τοποθεσία σας").openPopup();
            var coverage_circle = L.circle([{{ location.lat }}, {{ location.lon }}], {
            color: 'green',
            fillColor: '#bbe8b2',
            fillOpacity: 0.4,
            radius: 5000
        }).addTo(mymap);
          $("#table-event-filter-input").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#table-event tr").filter(function() {
              $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
          });
        });
        </script>
      </div>
    </div>
  </div>
<section/>
{% endif %}

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright © Lorem Ipsum 2018</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="https://github.com/epilys/lorem-ipsum">
              <i class="fa fa-github"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
</footer>
{% endblock %}

loremipsum/templates/provider_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block head_title %}{{ provider.full_name }} {{ block.super }}{% endblock %}
{% block content %}
<header class="masthead">
  <div class="container">
    <br><br>
    <img src="../../static/images/lorem-ipsum-profile-provider.png" width="50%" alt=""><br><br>
    <p> {{ provider.full_name }} </p><br>
  </div>
</header>

<section class="bg-light">
  <div class="container">
    <div class="row">
      <div class="col-lg-4"></div>
      <div class="col-lg-4 text-center">
        <p><strong>Logo</strong><br> <img src= "/{{provider.logo}}" ></p>
        <p><strong>Όνομα</strong> {{ provider.full_name }}</p>
        <p><strong>e-mail</strong> {{ provider.email }}</p>
        <p><strong>Διεύθυνση</strong> {{ provider.address}}</p>
        <p><strong>Ιστοσελίδα</strong> {{ provider.site }}</p>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <br><br><h5 class="text-center"> Δραστηριότητες από {{ provider.full_name }} </h5><br>
        <table class="table table-striped">
          <thead>
            <tr>
              <th>Τίτλος</th>
              <th>Ημερομηνία</th>
              <th>Διαθεσιμότητα</th>
            </tr>
          </thead>
          <tbody id="table-event">
            {% for e in event_list %}
            {% if e.availability == 0 %}
            <tr class="danger">
            {% else %}
            <tr>
              {% endif %}
              <td><a href="{{ e.get_absolute_url }}">{{ e.title }}</a></td>
              <td>{{ e.event_date }}</td>
              <td>{{ e.availability }}/{{ e.capacity }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
  </div>
</section>

<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <span class="copyright">Copyright © Lorem Ipsum 2018</span>
      </div>
      <div class="col-md-4">
        <ul class="list-inline social-buttons">
          <li class="list-inline-item">
            <a href="https://github.com/epilys/lorem-ipsum">
              <i class="fa fa-github"></i>
            </a>
          </li>
        </ul>
      </div>
      <div class="col-md-4"></div>
    </div>
  </div>
</footer>
{% endblock %}